/**
 * Méretmezők definíciói és mértékegységei.
 */
export const dimensionFields = {
  roofArea: {
    id: 'roofArea',
    label: 'Tetőfelület',
    unit: 'm²',
    placeholder: 'pl. 180',
    description: 'A teljes befedendő tetőfelület nagysága',
    image: '/wp-content/uploads/nyeregteto-rt-tetofelulet.svg',
  },
  ridge: {
    id: 'ridge',
    label: 'Gerinc',
    unit: 'fm',
    placeholder: 'pl. 12',
    description: 'Vízszintes tetőgerinc hossza',
    image: '/wp-content/uploads/nyeregteto-rt-tetogerinc.svg',
  },
  hip: {
    id: 'hip',
    label: 'Élgerinc',
    unit: 'fm',
    placeholder: 'pl. 8',
    description: 'Ferde élek, élgerincek hossza',
    image: '/wp-content/uploads/kontyolt-nyeregteto-rt-elgerinc.svg',
  },
  valley: {
    id: 'valley',
    label: 'Vápa',
    unit: 'fm',
    placeholder: 'pl. 6',
    description: 'Tetőhajlatok, vápa hossza',
    image: '/wp-content/uploads/nyeregteto-l-rt-vapa.svg',
  },
  eaves: {
    id: 'eaves',
    label: 'Eresz',
    unit: 'fm',
    placeholder: 'pl. 34',
    description: 'Ereszvonal teljes hossza',
    image: '/wp-content/uploads/nyeregteto-rt-eresz.svg',
  },
  verge: {
    id: 'verge',
    label: 'Orom',
    unit: 'fm',
    placeholder: 'pl. 18',
    description: 'Oromszegélyek teljes hossza',
    image: '/wp-content/uploads/nyeregteto-rt-oromszegely.svg',
  },
};

/**
 * Fő tetőformák és altípusok konfigurációja a hozzájuk tartozó egyedi jelmagyarázó képekkel.
 */
export const roofTypes = [
  {
    id: 'gable',
    name: 'Nyeregtető',
    description: 'Két lejtős tetősíkból álló hagyományos tetőforma',
    image: '/wp-content/uploads/nyeregteto-rt.svg',
    subtypes: [
      {
        id: 'gable-simple',
        name: 'Egyszerű nyeregtető',
        description: 'Hagyományos kétirányú tetőfelület',
        image: '/wp-content/uploads/nyeregteto-rt.svg',
        fields: ['roofArea', 'ridge', 'eaves', 'verge'],
        hasVerge: true,
        fieldImages: {
          roofArea: '/wp-content/uploads/nyeregteto-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/nyeregteto-rt-tetogerinc.svg',
          eaves: '/wp-content/uploads/nyeregteto-rt-eresz.svg',
          verge: '/wp-content/uploads/nyeregteto-rt-oromszegely.svg',
        },
      },
      {
        id: 'gable-l',
        name: 'L alakú nyeregtető',
        description: 'L alakban csatlakozó nyeregtetős szárnyakkal',
        image: '/wp-content/uploads/nyeregteto-l-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'valley', 'eaves', 'verge'],
        hasVerge: true,
        fieldImages: {
          roofArea: '/wp-content/uploads/nyeregteto-l-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/nyeregteto-l-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/nyeregteto-l-rt-elgerinc.svg',
          valley: '/wp-content/uploads/nyeregteto-l-rt-vapa.svg',
          eaves: '/wp-content/uploads/nyeregteto-l-rt-eresz.svg',
          verge: '/wp-content/uploads/nyeregteto-l-rt-oromszegely.svg',
        },
      },
      {
        id: 'gable-t',
        name: 'T alakú nyeregtető',
        description: 'T alakban kereszteződő nyeregtetős szárnyakkal',
        image: '/wp-content/uploads/nyeregteto-t-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'valley', 'eaves', 'verge'],
        hasVerge: true,
        fieldImages: {
          roofArea: '/wp-content/uploads/nyeregteto-t-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/nyeregteto-t-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/nyeregteto-l-rt-elgerinc.svg',
          valley: '/wp-content/uploads/nyeregteto-t-rt-vapa.svg',
          eaves: '/wp-content/uploads/nyeregteto-t-rt-eresz.svg',
          verge: '/wp-content/uploads/nyeregteto-t-rt-oromszegely.svg',
        },
      },
    ],
  },
  {
    id: 'hipped',
    name: 'Kontyolt nyeregtető',
    description: 'Négy lejtős tetősík, oromfalak nélkül',
    image: '/wp-content/uploads/kontyolt-nyeregteto-rt.svg',
    subtypes: [
      {
        id: 'hipped-simple',
        name: 'Egyszerű kontytető',
        description: 'Klasszikus 4 síkú kontyolt tető',
        image: '/wp-content/uploads/kontyolt-nyeregteto-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'eaves'],
        hasVerge: false,
        fieldImages: {
          roofArea: '/wp-content/uploads/kontyolt-nyeregteto-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/kontyolt-nyeregteto-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/kontyolt-nyeregteto-rt-elgerinc.svg',
          eaves: '/wp-content/uploads/kontyolt-nyeregteto-rt-eresz.svg',
        },
      },
      {
        id: 'hipped-l',
        name: 'L alakú kontytető',
        description: 'L alaprajzú kontyolt tetőforma vápával',
        image: '/wp-content/uploads/kontyolt-nyeregteto-l-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'valley', 'eaves'],
        hasVerge: false,
        fieldImages: {
          roofArea: '/wp-content/uploads/kontyolt-nyeregteto-l-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/kontyolt-nyeregteto-l-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/kontyolt-nyeregteto-l-rt-elgerinc.svg',
          valley: '/wp-content/uploads/kontyolt-nyeregteto-l-rt-vapa.svg',
          eaves: '/wp-content/uploads/kontyolt-nyeregteto-l-rt-eresz.svg',
        },
      },
      {
        id: 'hipped-t',
        name: 'T alakú kontytető',
        description: 'T alaprajzú összetett kontyolt tetőforma',
        image: '/wp-content/uploads/kontyolt-nyeregteto-t-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'valley', 'eaves'],
        hasVerge: false,
        fieldImages: {
          roofArea: '/wp-content/uploads/kontyolt-nyeregteto-t-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/kontyolt-nyeregteto-t-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/kontyolt-nyeregteto-t-rt-elgerinc.svg',
          valley: '/wp-content/uploads/kontyolt-nyeregteto-t-rt-vapa.svg',
          eaves: '/wp-content/uploads/kontyolt-nyeregteto-t-rt-eresz.svg',
        },
      },
    ],
  },
  {
    id: 'pyramid',
    name: 'Sátortető',
    description: 'Négy háromszög alakú, egy csúcsban találkozó sík',
    image: '/wp-content/uploads/satorteto-rt.svg',
    subtypes: [],
    fields: ['roofArea', 'hip', 'eaves'],
    hasVerge: false,
    fieldImages: {
      roofArea: '/wp-content/uploads/satorteto-rt-tetofelulet.svg',
      hip: '/wp-content/uploads/satorteto-rt-elgerinc.svg',
      eaves: '/wp-content/uploads/satorteto-rt-eresz.svg',
    },
  },
  {
    id: 'mansard',
    name: 'Manzárdtető',
    description: 'Tört lejtésű, meredek alsó síkokkal rendelkező tető',
    image: '/wp-content/uploads/manzardteto-rt.svg',
    subtypes: [
      {
        id: 'mansard-simple',
        name: 'Egyszerű manzárdtető',
        description: 'Tört síkú nyeregtető oromzattal',
        image: '/wp-content/uploads/manzardteto-rt.svg',
        fields: ['roofArea', 'ridge', 'eaves', 'verge'],
        hasVerge: true,
        fieldImages: {
          roofArea: '/wp-content/uploads/manzardteto-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/manzardteto-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/manzardteto-rt-elgerinc.svg',
          eaves: '/wp-content/uploads/manzardteto-rt-eresz.svg',
          verge: '/wp-content/uploads/manzardteto-rt-oromszegely.svg',
        },
      },
      {
        id: 'mansard-hipped',
        name: 'Manzárd kontytető',
        description: 'Tört síkú 4 oldalas kontyolt forma',
        image: '/wp-content/uploads/kontyolt-manzardteto-rt.svg',
        fields: ['roofArea', 'ridge', 'hip', 'eaves'],
        hasVerge: false,
        fieldImages: {
          roofArea: '/wp-content/uploads/kontyolt-manzardteto-rt-tetofelulet.svg',
          ridge: '/wp-content/uploads/kontyolt-manzardteto-rt-tetogerinc.svg',
          hip: '/wp-content/uploads/kontyolt-manzardteto-rt-elgerinc.svg',
          eaves: '/wp-content/uploads/kontyolt-manzardteto-rt-eresz.svg',
        },
      },
    ],
  },
  {
    id: 'custom',
    name: 'Egyedi tetőforma',
    description: 'Összetett vagy speciális geometriájú tető',
    image: '/wp-content/uploads/egyedi-teto-rt.svg',
    subtypes: [],
    fields: ['roofArea', 'ridge', 'hip', 'valley', 'eaves', 'verge'],
    hasVerge: true,
    fieldImages: {
      roofArea: '/wp-content/uploads/egyedi-teto-rt-tetofelulet.svg',
      ridge: '/wp-content/uploads/egyedi-teto-rt-tetogerinc.svg',
      hip: '/wp-content/uploads/egyedi-teto-rt-elgerinc.svg',
      eaves: '/wp-content/uploads/egyedi-teto-rt-eresz.svg',
      valley: '/wp-content/uploads/nyeregteto-l-rt-vapa.svg',
      verge: '/wp-content/uploads/nyeregteto-rt-oromszegely.svg',
    },
  },
];

